global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "telemetry-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["event-platform-alb-95530675.us-east-1.elb.amazonaws.com:8000"]
        labels:
          service: "telemetry-api"
          environment: "production"

  - job_name: "analytics-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["event-platform-alb-95530675.us-east-1.elb.amazonaws.com:8001"]
        labels:
          service: "analytics-api"
          environment: "production"

  - job_name: "processor"
    metrics_path: "/metrics"
    ec2_sd_configs:
      - port: 8002
        filters:
          - name: tag:Service
            values: ["event-platform-processor"]
