global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "telemetry-api"
    static_configs:
      - targets: ["telemetry-api:8000"]

  - job_name: "event-processor"
    static_configs:
      - targets: ["event-processor:8002"]

  - job_name: "analytics-api"
    static_configs:
      - targets: ["analytics-api:8001"]


