global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "telemetry-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["10.0.1.248:8000"]
        labels:
          service: telemetry-api
          environment: production

  - job_name: "analytics-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["10.0.1.12:8001"]
        labels:
          service: analytics-api
          environment: production
