global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "telemetry-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: [""]
        labels:
          service: "telemetry-api"
          environment: "production"

  - job_name: "analytics-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: [""]
        labels:
          service: "analytics-api"
          environment: "production"