global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "telemetry-api"
    metrics_path: "/metrics"
    ecs_sd_configs:
      - region: us-east-1
        cluster: event-platform-cluster
        port: 8000
        filters:
          - name: service-name
            values: ["event-platform-telemetry-api"]
    relabel_configs:
      - source_labels: [__meta_ecs_service_name]
        target_label: service
      - target_label: environment
        replacement: production

  - job_name: "analytics-api"
    metrics_path: "/metrics"
    ecs_sd_configs:
      - region: us-east-1
        cluster: event-platform-cluster
        port: 8001
        filters:
          - name: service-name
            values: ["event-platform-analytics-api"]
    relabel_configs:
      - source_labels: [__meta_ecs_service_name]
        target_label: service
      - target_label: environment
        replacement: production

  - job_name: "processor"
    metrics_path: "/metrics"
    ec2_sd_configs:
      - region: us-east-1
        port: 8002
        filters:
          - name: tag:Service
            values: ["event-platform-processor"]

