global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "telemetry-api"
    metrics_path: "/metrics"
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/telemetry-api.json
        refresh_interval: 30s
    relabel_configs:
      - target_label: service
        replacement: telemetry-api
      - target_label: environment
        replacement: production

  - job_name: "analytics-api"
    metrics_path: "/metrics"
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/analytics-api.json
        refresh_interval: 30s
    relabel_configs:
      - target_label: service
        replacement: analytics-api
      - target_label: environment
        replacement: production

  - job_name: "processor"
    metrics_path: "/metrics"
    ec2_sd_configs:
      - port: 8002
        filters:
          - name: tag:Service
            values: ["event-platform-processor"]
